[package]
name = "srand"
version = "0.1.0"
authors = ["Netherdrake"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = "0.2"
blake2b_simd = "0.5.11"
rand = {version = "*", features = ['small_rng']}
